# !/bin/bash

# Change
KITTI_SEQUENCE=00
DEPTH_MODEL=mono_640x192
KITTI_META=KITTI_TEST.yaml

# Base Dirs
TX2_ORB_DIR=~/VSLAM-2020/ThirdParty/orbslam2
DATA_BASE_DIR=/media/vslam/SSD250
EXEUTABLE=~/VSLAM-2020/build/MONODEPTH_SLAM

VOCAB_FILE=${TX2_ORB_DIR}/Vocabulary/ORBvoc.txt
CONFIG_FILE=${DATA_BASE_DIR}/yaml/${KITTI_META}
RGB_DIR=${DATA_BASE_DIR}/data/kitti-rgb-output/${KITTI_SEQUENCE}/rgb
OUTPUT_DIR=${DATA_BASE_DIR}/data/kitti-rgb-output/${KITTI_SEQUENCE}/output
DEPTH_ENCODER=${DATA_BASE_DIR}/models/${DEPTH_MODEL}/t_encoder.pt
DEPTH_DECODER=${DATA_BASE_DIR}/models/${DEPTH_MODEL}/t_decoder.pt


${EXEUTABLE} ${RGB_DIR} ${OUTPUT_DIR} ${DEPTH_ENCODER} ${DEPTH_DECODER} ${VOCAB_FILE} ${CONFIG_FILE}
